name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v5

      - name: Setup Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          version: v0.72.0
          skip-setup-trivy: false
          scan-type: fs
          scan-ref: .
          exit-code: 0

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
